### ISSUE TITLE
Update github.io page with checklist requirements

### ISSUE THREAD

**Issue by montoyaoa** [rio-connect/rio-connect.github.io#1]

**Comment by montoyaoa** [comment]
Meets requirements:

- [x] Link to GitHub organization.

- [x] Link to the team contract.

- [x] Deployment section with a link to the deployed application.

- [x] Up-to-date screenshots.

- [x] Link to the M1 project board.

- [x] Link to the M2 project board.
